title = "PLURA XDR – Cloud SaaS Platform w/ MITRE ATT&CK"
baseURL = "https://blog.plura.io"
languageCode = "en"
defaultContentLanguageInSubdir = true
theme = "ananke"
buildFuture = true
copyright = "© 2014-2026 Qubit Security Inc. All Rights Reserved."

SectionPagesMenu = ""
googleAnalytics = ""
enableRobotsTXT = true

[pagination]
pagerSize = 8

[languages]
  [languages.ja]
    languageCode = "ja"
    title = "PLURA Blog"
    weight = 2
    languageName = "日本語"
    contentDir = "content/ja"

    [languages.ja.params]
      lang = "ja"
      background_image = "/images/ja-bg.png"
      summaryLength = 30

  [languages.en]
    languageCode = "en"
    title = "PLURA Blog"
    weight = 3
    languageName = "English"
    contentDir = "content/en"

    [languages.en.params]
      lang = "en"
      background_image = "/images/en-bg.jpg"
      summaryLength = 30

  [languages.ko]
    languageCode = "ko"
    title = "PLURA Blog"
    weight = 1
    languageName = "한국어"
    contentDir = "content/ko"

    [languages.ko.params]
      lang = "ko"
      background_image = "/images/ko-bg.png"
      summaryLength = 30

# ✅ 한국어 메뉴
[[menu.ko]]
name = "Column"
url = "/ko/column/"
weight = 1

[[menu.ko]]
name = "Tech"
url = "/ko/tech/"
weight = 2

[[menu.ko]]
name = "Threats"
url = "/ko/threats/"
weight = 3

[[menu.ko]]
name = "Respond"
url = "/ko/respond/"
weight = 4

[[menu.ko]]
name = "QnA"
url = "/ko/qna/"
weight = 5

[[menu.ko]]
name = "News"
url = "https://www.qubitsec.com/news"
weight = 6
params.target = "_blank"

# ✅ 일본어 메뉴
[[menu.ja]]
name = "コラム"
url = "/ja/column/"
weight = 1

[[menu.ja]]
name = "技術"
url = "/ja/tech/"
weight = 2

[[menu.ja]]
name = "脅威"
url = "/ja/threats/"
weight = 3

[[menu.ja]]
name = "対応"
url = "/ja/respond/"
weight = 4

[[menu.ja]]
name = "QnA"
url = "/ja/qna/"
weight = 5

[[menu.ja]]
name = "ニュース"
url = "https://www.damda.cloud/news"
weight = 6
params.target = "_blank"

# ✅ 영어 메뉴
[[menu.en]]
name = "Column"
url = "/en/column/"
weight = 1

[[menu.en]]
name = "Tech"
url = "/en/tech/"
weight = 2

[[menu.en]]
name = "Threats"
url = "/en/threats/"
weight = 3

[[menu.en]]
name = "Respond"
url = "/en/respond/"
weight = 4

[[menu.en]]
name = "QnA"
url = "/en/qna/"
weight = 5

[[menu.en]]
name = "News"
url = "https://w.qubitsec.com/en/news.html"
weight = 6
params.target = "_blank"

[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"

[params]
  text_color = ""
  author = "PLURA"
  favicon = "/images/favicon.ico"
  site_logo = ""
  background_color_class = "bg-black"
  description = "PLURA-XDR provides an integrated, real-time cybersecurity solution for detecting, analyzing, and responding to evolving cyber threats with EDR, WAF, Forensic, SIEM."
  recent_posts_number = 50
  googleFonts = "https://fonts.googleapis.com/css2?family=Playfair+Display:wght@500;700&display=swap"
  customCSS = true
  css_file = ["/css/fonts.css", "/css/main.css"]
  summaryLength = 500
  mainSections = ["respond", "column", "tech", "threats"]
  contentFontFamily = "'Roboto', sans-serif"
  contentLineHeight = "1.8"
  contentFontSize = "1.1rem"
  contentColor = "#333"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[outputs]
home = ["HTML", "RSS"]
